afeez01/Skeleton

- AdminSystem/StockDataEntry.aspx
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStock.cs
- Testing3/TestingStock.csproj
- Testing3/tstStock.cs
> Added testing for stock class

- ClassLibrary/clsStock.cs
- Testing3/tstStock.cs
> Creating the properties for Stock/Tool table design(W20)

- Testing1/TestingStaff.csproj
- Testing1/tstStaff.cs
> Added testing for staff class

- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
> Added properties for the table design

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockViewer.aspx.cs
- Skeleton.sln
> Adding a Basic Presentation Layer - Week21

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffViewer.aspx.cs
> Added a simple interface

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerViewer.aspx.cs
- Skeleton.sln
> finished week 21

- ClassLibrary/clsStock.cs
- Testing3/tstStock.cs
> Creating the Find Method - Week 23

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsDataConnection.cs
- ClassLibrary/clsStock.cs
- Testing3/tstStock.cs
> Creating the Data Layer and the class clsDataConnnection

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
> Adding the Presentation Layer

- ClassLibrary/clsOrder.cs
- Testing4/tstOrder.cs
Added testing for methods in tst Order.
> Created method for cls Order.

- AdminSystem/OrdersDataEntry.aspx
- AdminSystem/OrdersDataEntry.aspx.cs
- ClassLibrary/clsOrder.cs
- Testing4/tstOrder.cs
Made changes for clsOrder and tstOrder.
> Added the presentation layer for find method.

- ClassLibrary/clsStock.cs
- Testing3/tstStock.cs
> Adding Validation - Week 24

- AdminSystem/StockDataEntry.aspx.cs
- ClassLibrary/clsStock.cs
> Adding Validation - Presentation

- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- ClassLibrary/clsStockCollection.cs
- Testing3/tstStockCollection.cs
> Creating the Collection Class (Properties) - part 2

- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- ClassLibrary/clsStockCollection.cs
- Testing3/tstStockCollection.cs
> Creating the Method (Add)

- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- ClassLibrary/clsStockCollection.cs
- Testing3/tstStockCollection.cs
> Creating the Methods ( Update)

- AdminSystem/OrdersDataEntry.aspx
- AdminSystem/OrdersDataEntry.aspx.cs
- AdminSystem/OrdersList.aspx
- AdminSystem/OrdersList.aspx.cs
- Testing4/tstOrderCollection.cs
Finished creating collection class
> Changes the code for tstOrderCollection.

- AdminSystem/OrdersList.aspx
- AdminSystem/OrdersList.aspx.cs
- ClassLibrary/clsOrderCollection.cs
- Testing4/tstOrderCollection.cs
> Created the Shipping Address Filter.

- AdminSystem/StaffDataEntry.aspx.cs
- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
> Created the find method

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffViewer.aspx.cs
- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
> Added validation - Middle Layer

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
- ClassLibrary/clsStock.cs
- Testing3/tstStock.cs
> Updated the code

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsOrderLine.cs
- ClassLibrary/clsOrderLineCollection.cs
- Skeleton.sln
- Testing6/TestingOrderLine.csproj
- Testing6/tstOrderLine.cs
- Testing6/tstOrderLineCollection.cs
Created the class for orderline and orderlineCollection.
> Created Testing for orderLine and orderLineCollection.

- AdminSystem/StaffConfirmDelete.aspx
- AdminSystem/StaffConfirmDelete.aspx.cs
- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaffCollection.cs
- Testing1/tstStaffCollection.cs
> Created the Delete method

- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- AdminSystem/SuppliersDataEntry.aspx
- ClassLibrary/clsStaffCollection.cs
- Testing1/tstStaffCollection.cs
- dbo.sproc_tblStaff_FilterByFullName.sql
> Created the Filter method
